name: "CI Tests"

on:
  - "pull_request"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        hotwire-enabled:
          - true
          - false
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        rails-version:
          - "7.1"
          - "7.0"
          - "6.1"
          - "main"
        selenium-browser:
          - "headless_chrome"
          - "headless_firefox"
        exclude:
          - ruby-version: "2.7"
            rails-version: "main"
          - ruby-version: "3.0"
            rails-version: "main"

    env:
      RAILS_VERSION: "${{ matrix.rails-version }}"
      SELENIUM_BROWSER: "${{ matrix.selenium-browser }}"

    name: ${{ format('Tests (Ruby {0}, Rails {1}, Browser {2}, Hotwire {3})', matrix.ruby-version, matrix.rails-version, matrix.selenium-browser, matrix.hotwire-enabled) }}
    runs-on: "ubuntu-latest"

    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-node@v2"
      with:
        cache: "yarn"
    - uses: "ruby/setup-ruby@v1"
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: |
        yarn install
        yarn build

    - run: bin/rails test test/**/*_test.rb

    - name: Fail when generated changes are not checked-in
      run: |
        git update-index --refresh
        git diff-index --quiet HEAD --
